server_url = "https://download.geofabrik.de/"
suffix = "-latest"

[regions]
russia = []
europe = [
	"albania",
	"andorra",
	"austria",
	"azores",
	"belarus",
	"belgium",
	"bosnia-herzegovina",
	"bulgaria",
	"croatia",
	"cyprus",
	"czech-republic",
	"denmark",
	"estonia",
	"faroe-islands",
	"finland",
	"france",
	"georgia",
	"germany",
	"great-britain",
	"greece",
	"guernsey-jersey",
	"hungary",
	"iceland",
	"ireland-and-northern-ireland",
	"isle-of-man",
	"italy",
	"kosovo",
	"latvia",
	"liechtenstein",
	"lithuania",
	"luxembourg",
	"macedonia",
	"malta",
	"moldova",
	"monaco",
	"montenegro",
	"netherlands",
	"norway",
	"poland",
	"portugal",
	"romania",
	"serbia",
	"slovakia",
	"slovenia",
	"spain",
	"sweden",
	"switzerland",
	"turkey",
	"ukraine",
]
